[build]
  command = "npm run build"
  publish = "build"

[context.production.environment]
  NODE_ENV = "production"
  REACT_APP_API_URL = "https://api.example.com"
  REACT_APP_ENV = "production"

[context.staging.environment]
  NODE_ENV = "staging"
  REACT_APP_API_URL = "https://staging-api.example.com"
  REACT_APP_ENV = "staging"